---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ott-prime-app
  labels:
    app: ott-prime-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ott-prime-app
  template:
    metadata:
      labels:
        app: ott-prime-app
    spec:
      containers:
      - name: ott-prime-container
        image: 859384797911.dkr.ecr.ap-southeast-1.amazonaws.com/ott-prime:${BUILD_NUMBER}
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
...
